services:
  spade:
    image: ghcr.io/slmingol/spade--dns-inspector:latest
    container_name: spade
    ports:
      - "8484:80"
    restart: unless-stopped
    environment:
      - SERVER_CONFIG_FILE=/sws.toml
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
