[general]
root = "/public"
port = 80
log-level = "error"

[[advanced.headers]]
source = "**"
[advanced.headers.headers]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src https://dns.google https:"
